minimum_pre_commit_version: 2.9.2
repos:
-   repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
